language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
env:
  global:
    secure: lzLnYwUXHzX+OtZXTp+qLDuqK9h4gmM1Uu6PczZ/V5MSMOMYUd4Lww5zF7otwuo5wLdUOOT/ImD8obCOYZI0ouJ8OHjVonFa93Rn81OJAvG337E92ymzPNltdvqVChazTxJgYhWBLDjEG9zvpmJVOZBHMKPjLMF+Jgm1c52djxJpZD0jN/VqDQpfwYpUKBZrp1reEcCWYcn0VQmHU69aWIx5mZg/VXuCFDC4InoYA+NJbRiWsPtYTfrgSu/yJcVlYs/ZCpIRxJnhe7u63yI8ZodAdoCcMM391LelD8+CBhndnELs7hvW/163Jh3UgWYaXOzBvuMY9VdilwUWrVtMcp3AxUNdOf3AujSX5VyHyJUfg63LeHnEe2aw+IdYIY8dwBFjg22poLqLw/I4SRyVW/zT/veex+TH7z1+ptDMxqxNh8LtjgCchEQH48MGWpLzmtNjR3bY1PG+3ep2BIkjZG9kZgy+rjNixyWk1Ah3deKRtqEvZaJqJXlWp3VUp4DWUSzo+wIBOoLAwGLkWTKnuaE8zOzfLMwcIxfhrnFyhWqZJmVoE53ZPUl7PzF9jAFjkoUGsVdmyEjvIxMo3JALDEX3+UY1U8TLIENwOGTIlaThdD1QS5VEcLLI1kSO3S5SnyhljtUqf+aVv4vDtztguOZOSOqvl3ll34TenIrvn7c=
after_success:
  - ./.travis/create_branch.sh
