language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
env:
  global:
    secure: "f9dCOmDDiOb9cMa+bkos4IsWIpBS1ujMs5FZtVxxGOidHrlujy1tBJ664IvyB/LudTN18+GHlqKdXnfCtL8628uxAQKbWdR5HTHUd3vmg995P4BToQu5jwVOVzkSTbm9ZotsKEF9s03dwiIJMq9wg8iMaDX8nyQbkvOjBcPkei4J2KoagJXYml+tP0qCS1rx3IzW+25WTDLGHQvy9cU8UpZHBkwm5Opfas6IRA22patSOYrPU/NYOmP4IwOnRwCJ0YBx6u7THIr+tgiQHSWiw4KO1IN1/cfZxPqMMrFfZP6jHFfEWpEF6cdaVHuzMco28+L/Gbw7JMdiGn1E2j0TtEySJI/C3pzwVGmz3fmcwoybPuge3KQDMItgT55uAUGLClT1X/8OmP8Xvn9JRHWDAM/C/IVkcT5JQHnkVublmRTp+F3KKvB/Ary8AY9pkIGdlTStdPhXj+SGvCxMjcG679nGZcQUQpeOM+4Yyo1kirasbGMfN2dzO6NqSMyqc43DdGYF6JRwx7Ic0pINch17+gmr6kwnmgX/WToSxjjicNF6CYgs59kZyDvviPLYrRlBRa81fB5FkpsJofoCn7CBqJqsrN9JgJ3TlIJ0qz3dKzSmZXV489gjkFI6Q26/ybm/HqUNTq2awaPCjda4dbsUUNVmIEZ59MsWoGNm22OVZJc="
after_success:
  - ./.travis/create_branch.sh
